language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
before_install:
  - pip install coveralls
install:
  - pip install -e .
  - pip install -r tests/requirements.txt
  - pip install Django==${DJANGO}
script: make test
env:
  - DJANGO=1.9.13
  - DJANGO=1.10.7
  - DJANGO=1.11.1
matrix:
  exclude:
    - python: 3.6
      env: DJANGO=1.9.13
    - python: 3.6
      env: DJANGO=1.10.7
after_success:
  - coveralls
